import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';

export interface PeriodicElement {
    name: string;
    description: string;
  }
  
  const ELEMENT_DATA: PeriodicElement[] = [
    {name: 'Date', description: 'Exact date of hearing between 2010 and 2020'},
    {name: 'Category Title', description: 'Official title of the category according to ECB website'},
    {name: 'Topic', description: 'Financial topic generated by Text Mining'},
    {name: 'Financial Sentiment', description: 'Financial Sentiment between 1 (very positive) and 0 (very negative)'},
    {name: 'Exact Starttime', description: 'Exact starttime for every category'},
    { name: 'Exact Endtime', description: 'Exact endtime for every category'},
    {name: 'Raw Text of Category',description: 'Raw text'},

  ];

@Component({
  selector: 'app-ecbhearings',
  templateUrl: './ecbhearings.component.html',
  styleUrls: ['./ecbhearings.component.scss']
})
export class EcbhearingsComponent implements OnInit {

  chartOptions: {};
  Highcharts = Highcharts;
  constructor() { }

  displayedColumns: string[] = [ 'name', 'description'];
  dataSource = ELEMENT_DATA;
  ngOnInit() {
    HC_exporting(Highcharts);
    this.chartOptions = {

      title: {
        text: 'Financial Tone in ECB Hearings'
    },

    subtitle: {
        text: 'Source: sophiadata'
    },

    yAxis: {
        title: {
            text: 'Number of Employees'
        }
    },
    legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle'
    },

    plotOptions: {
        series: {
            label: {
                connectorAllowed: false
            },
            pointStart: 2010
        }
    },

    series: [{
        name: 'Installation',
        data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
    }, {
        name: 'Manufacturing',
        data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
    }, {
        name: 'Sales & Distribution',
        data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
    }, {
        name: 'Project Development',
        data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
    }, {
        name: 'Other',
        data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
    }],

    responsive: {
        rules: [{
            condition: {
                maxWidth: 500
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    },
    
    

    }
  }
}
